global:
  scrape_interval:     3ms
  evaluation_interval: 3ms

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'tsdbb-prometheus-client'

scrape_configs:

  - job_name:    'pushgateway'

    honor_labels: true

    # Override the global default and scrape targets from this job every 5 seconds.

    static_configs:
      - targets: ['localhost:9091']


