#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "Copying Files to vagrant_files/generator/..."
cp RunWorkload.py vagrant_files/generator/files/RunWorkload.py
if [ $? -ne 0 ]; then
    echo "Error: 'cp RunWorkload.py vagrant_files/generator/files/RunWorkload.py' did not return 0"
fi
cp -r databases vagrant_files/generator/files/
if [ $? -ne 0 ]; then
    echo "Error: 'cp -r databases vagrant_files/generator/files/' did not return 0"
fi
git commit --no-verify vagrant_files/generator/files/RunWorkload.py databases vagrant_files/generator/files/*
exit 0